# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[build-system]
requires = ["setuptools >= 65"]
build-backend = "setuptools.build_meta"


[project]
name = "comma"
description = "Linux Commit Analyzer"
classifiers = [
    "Programming Language :: Python :: 3",
    "Development Status :: 5 - Production/Stable",
    "Topic :: Software Development",
]
dependencies = [
  "gitpython ~= 3.1.0",
  "pyodbc ~= 4.0.30",
  "python-Levenshtein ~= 0.12.0",
  "fuzzywuzzy ~= 0.18.0",
  "sqlalchemy ~= 1.3.13",
  "openpyxl ~= 3.0.4",

]
dynamic = ["version"]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.8"
authors = [
  {name = "Ryan Feldman", email = "ryfeldma@microsoft.com"},
  {name = "Abhishek Marathe", email = "abmarath@microsoft.com"},
  {name = "Andrew Schwartzmeyer", email = "andrew@schwartzmeyer.com"},
]

[project.scripts]
comma = "comma.__main__:main"

[project.optional-dependencies]
flake8 = [
  "flake8 ~= 3.7.9",
  "flake8-bugbear ~= 20.1.4",
]

black = [
  "black ~= 19.10b0",
]

isort = [
  "isort ~= 4.3.21",
]

[project.urls]
homepage = "https://github.com/microsoft/Linux-CommA"

[tool.black]

[tool.setuptools.packages.find]
include = ["comma*"]
namespaces = false

[tool.setuptools.dynamic]
version = {attr = "comma.__version__"}